export default [
  {
    id: 1,
    name: "Katrina Cox",
    jobOpening: "Software Engineer",
    status: "Offer Sent",
    lastUpdate: "9 days",
    phone: "999999999",
    avatarUrl: '/images/avatars/avatar_1.png',
  },
  {
    id: 1,
    name: "Janet Lewis",
    jobOpening: "General Application",
    status: "Offer Sent",
    lastUpdate: "9 days",
    phone: "999999999",
    avatarUrl: '/images/avatars/avatar_2.png',
  },
  {
    id: 1,
    name: "John Stone",
    jobOpening: "Software Engineer",
    status: "Offer Sent",
    lastUpdate: "9 days",
    phone: "999999999",
    avatarUrl: '/images/avatars/avatar_3.png',
  },
  {
    id: 1,
    name: "Kelli Colburn",
    jobOpening: "IT Security Engineer",
    status: "Offer Sent",
    lastUpdate: "9 days",
    phone: "999999999",
    avatarUrl: '/images/avatars/avatar_4.png',
  },
  {
    id: 1,
    name: "Anderson Pierce",
    jobOpening: "Software Engineer",
    status: "Offer Sent",
    lastUpdate: "9 days",
    phone: "999999999",
    avatarUrl: '/images/avatars/avatar_5.png',
  },
  {
    id: 1,
    name: "April Kivlin",
    jobOpening: "General Application",
    status: "Offer Sent",
    lastUpdate: "9 days",
    phone: "999999999",
    avatarUrl: '/images/avatars/avatar_6.png',
  },
  {
    id: 1,
    name: "Jeremy Steel",
    jobOpening: "IT Security Engineer",
    status: "Offer Sent",
    lastUpdate: "9 days",
    phone: "999999999",
    avatarUrl: '/images/avatars/avatar_7.png',
  },
];
