// import uuid from 'uuid/v1';

export default [
  {
    id: 1,
    name: 'Ekaterina Tankova',
    type: "Full Time",
    status: "Onboarding",
    department:'Department1',
    title: "Instructor",
    section: "Electrical maintenance Vinyl",
    hiring: "1/01/64",
    manager: 'Ekaterina Tankova',
    province:'Rayong',
    email: 'ekaterina.tankova@devias.io',
    phone: '304-428-3097',
    avatarUrl: '/images/avatars/avatar_3.png',
    createdAt: 1555016400000
  },
  {
    id: 2,
    name: 'Cao Yu',
    type: "Full Time",
    status: "Terminated",
    department:'Department2',
    title: "Instructor",
    section: "Electrical maintenance Vinyl",
    hiring: "1/01/64",
    manager: 'Ekaterina Tankova',
    province:'Bangkok',
    email: 'cao.yu@devias.io',
    avatarUrl: '/images/avatars/avatar_4.png',
    phone: '712-351-5711',
    createdAt: 1555016400000
  },
  {
    id: 3,
    name: 'Alexa Richardson',
    type: "Full Time",
    status: "Active",
    department:'Department1',
    title: "Instructor",
    section: "Electrical maintenance Vinyl",
    hiring: "1/01/64",
    manager: 'Ekaterina Tankova',
    province:'Rayong',
    email: 'alexa.richardson@devias.io',
    phone: '770-635-2682',
    avatarUrl: '/images/avatars/avatar_2.png',
    createdAt: 1555016400000
  },
  {
    id: 4,
    name: 'Anje Keizer',
    type: "Full Time",
    status: "Active",
    department:'Department1',
    title: "Instructor",
    section: "Electrical maintenance Vinyl",
    hiring: "1/01/64",
    manager: 'Ekaterina Tankova',
    province:'Bangkok',
    email: 'anje.keizer@devias.io',
    avatarUrl: '/images/avatars/avatar_5.png',
    phone: '908-691-3242',
    createdAt: 1554930000000
  },
  {
    id: 5,
    name: 'Clarke Gillebert',
    type: "Full Time",
    status: "Terminated",
    department:'Department2',
    title: "Instructor",
    section: "Electrical maintenance Vinyl",
    hiring: "1/01/64",
    manager: 'Ekaterina Tankova',
    province:'Rayong',
    email: 'clarke.gillebert@devias.io',
    phone: '972-333-4106',
    avatarUrl: '/images/avatars/avatar_6.png',
    createdAt: 1554757200000
  },
  {
    id: 6,
    name: 'Adam Denisov',
    type: "Part Time",
    status: "Active",
    department:'Department3',
    title: "Trainer",
    section: "Electrical maintenance Vinyl",
    hiring: "1/01/64",
    manager: 'Ekaterina Tankova',
    province:'Bangkok',
    email: 'adam.denisov@devias.io',
    phone: '858-602-3409',
    avatarUrl: '/images/avatars/avatar_1.png',
    createdAt: 1554670800000
  },
  {
    id: 7,
    name: 'Ava Gregoraci',
    type: "Part Time",
    status: "Terminated",
    department:'Department1',
    title: "Trainer",
    section: "Electrical maintenance Vinyl",
    hiring: "1/01/64",
    manager: 'Ekaterina Tankova',
    province:'Rayong',
    email: 'ava.gregoraci@devias.io',
    avatarUrl: '/images/avatars/avatar_7.png',
    phone: '415-907-2647',
    createdAt: 1554325200000
  },
  {
    id: 8,
    name: 'Emilee Simchenko',
    type: "Part Time",
    status: "Active",
    department:'Department2',
    title: "Trainer",
    section: "Electrical maintenance Vinyl",
    hiring: "1/01/64",
    manager: 'Ekaterina Tankova',
    province:'Bangkok',
    email: 'emilee.simchenko@devias.io',
    phone: '702-661-1654',
    avatarUrl: '/images/avatars/avatar_8.png',
    createdAt: 1523048400000
  },
  {
    id: 9,
    name: 'Kwak Seong-Min',
    type: "Part Time",
    status: "Terminated",
    department:'Department3',
    title: "Trainer",
    section: "Electrical maintenance Vinyl",
    hiring: "1/01/64",
    manager: 'Ekaterina Tankova',
    province:'Rayong',
    email: 'kwak.seong.min@devias.io',
    avatarUrl: '/images/avatars/avatar_9.png',
    phone: '313-812-8947'
  },
  {
    id: 10,
    name: 'Merrile Burgett',
    type: "Part Time",
    status: "Active",
    department:'Department1',
    title: "Trainer",
    section: "Electrical maintenance Vinyl",
    hiring: "1/01/64",
    manager: 'Ekaterina Tankova',
    province:'Bangkok',
    email: 'merrile.burgett@devias.io',
    phone: '801-301-7894',
    avatarUrl: '/images/avatars/avatar_10.png',
    createdAt: 1522702800000
  },
  
];
