export default [
  {
    id: 1,
    name: "Katrina Cox",
    position: "HR Manager",
    department: "HR Office",
    section: "AAA",
    lastUpdate: "21/2/2022",
    picUrl: '/images/avatars/avatar_1.png',
  },
  {
    id: 1,
    name: "Janet Lewis",
    position: "HR Manager",
    department: "HR Office",
    section: "BBB",
    lastUpdate: "21/2/2022",
    picUrl: "/images/avatars/avatar_2.png",
  },
  {
    id: 1,
    name: "John Stone",
    position: "Programmer",
    department: "Pro",
    section: "CCC",
    lastUpdate: "21/2/2022",
    picUrl: "/images/avatars/avatar_3.png",
  },
  {
    id: 1,
    name: "John Stonea",
    position: "HR Manager",
    department: "HR Office",
    section: "DDD",
    lastUpdate: "21/2/2022",
    picUrl: "/images/avatars/avatar_4.png",
  },
  {
    id: 1,
    name: "Anderson Pierce",
    position: "Programmer",
    department: "Pro",
    section: "EEE",
    lastUpdate: "21/2/2022",
    picUrl: "/images/avatars/avatar_5.png",
  },
  {
    id: 1,
    name: "April Kivlin",
    position: "Programmer",
    department: "Pro",
    section: "FFF",
    lastUpdate: "21/2/2022",
    picUrl: "/images/avatars/avatar_6.png",
  },
  {
    id: 1,
    name: "Jeremy Steel",
    position: "Programmer",
    department: "Pro",
    section: "GGG",
    lastUpdate: "21/2/2022",
    picUrl: "/images/avatars/avatar_7.png",
  },
  {
    id: 1,
    name: "changsth",
    position: "Programmer",
    department: "Pro",
    section: "HHH",
    lastUpdate: "21/2/2022",
    picUrl: "/images/avatars/avatar_8.png",
  },
  {
    id: 1,
    name: "change th",
    position: "Programmer",
    department: "Pro",
    section: "III",
    lastUpdate: "21/2/2022",
    picUrl: "/images/avatars/avatar_9.png",
  },
  {
    id: 1,
    name: "change ",
    position: "Programmer",
    department: "Pro",
    section: "JJJ",
    lastUpdate: "21/2/2022",
    picUrl: "/images/avatars/avatar_10.png",
  },
];
